# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 08:36
"do a migration thingy"
from __future__ import unicode_literals
import datetime
from django.utils import timezone

from django.db import migrations

import faker



def forwards(apps, schema_editor):
    ' apply changes from migration '
    print schema_editor
    Poll = apps.get_model("polls", "Poll")
    Question = apps.get_model("polls", "Question")
    generator = faker.Faker()
    question1 = Question.objects.create(question_text='What is your favorite color?',
                                        pub_date=datetime.datetime.now())
    for _ in range(5):
        question1.choice_set.create(choice_text=generator.color_name())
    question2 = Question.objects.create(question_text='What is your timezone?',
                                        pub_date=timezone.now())
    for _ in range(5):
        question2.choice_set.create(choice_text=generator.timezone())
    p = Poll.objects.create(name='First Poll')
    p.questions.add(question1, question2)
    # data = read_jsondata()


def backwards(apps, schema_editor):
    ' remove changes in migration '
    print 'going backwards', apps, schema_editor


class Migration(migrations.Migration):
    'class to do a custom migration'
    dependencies = [
        ('polls', '0002_poll'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
